substitutions:
  name: esphome-web-ec63c0
  friendly_name: HVAC

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: esphome.web
    version: dev

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  encryption:
    key: FI3nDLDCOGRv9BYFFgg99ag12/P6nm9VU9aROVNtz3o=

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: "!Thebel143"  # You can set this to something secure

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

#dashboard_import:
#  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
#  import_full_config: true

dashboard_import:
  package_import_url: github://ryansch/esphome-config/waveshare-esp32-s3-relay-6ch.yaml@main
  import_full_config: true

time:
  - platform: homeassistant
    id: homeassistant_time

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

# Reference the temperature sensor from Home Assistant (living room sensor)
sensor:
  - platform: homeassistant
    id: temperature_sensor
    name: "Temperature Sensor from Living Room"
    entity_id: sensor.esphome_web_fab2b8_temperature  # Use the actual entity ID for the BME680 sensor from Home Assistant
    unit_of_measurement: °F
    filters:
      - lambda: return (x - 32.0) * 5.0 / 9.0;  # Fahrenheit to Celsius conversion, if needed

  # WiFi Signal Strength
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic

binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    name: "Boot Button"
    pin:
      number: 0
      ignore_strapping_warning: true
      mode:
        input: true
      inverted: true
    disabled_by_default: true

text_sensor:
  - platform: version
    name: "Firmware Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic

# Led indicator light
light:
   - platform: neopixelbus
     type: RGB
     variant: 800KBPS
     pin: GPIO38
     num_leds: 1
     name: "HVAC Status LED"
     id: hvac_status_led


switch:
  # Relay 1
  - platform: gpio
    pin: GPIO1
    id: G
    name: "Fan"
  # Relay 2
  - platform: gpio
    pin: GPIO2
    id: W1
    name: "Low Heat"
  # Relay 3
  - platform: gpio
    pin: GPIO41
    id: W2
    name: "High Heat"
  # Relay 4
  - platform: gpio
    pin: GPIO42
    id: Y1
    name: "Cool"
  # Relay 5
  - platform: gpio
    pin:
      number: GPIO45
      ignore_strapping_warning: true
    id: relay5
    name: Relay 5
  # Relay 6  
  - platform: gpio
    pin:
      number: GPIO46
      ignore_strapping_warning: true
    id: relay6
    name: Relay 6

  - platform: restart
    name: "Restart"
    id: restart_button
    entity_category: config

  - platform: factory_reset
    name: "Factory Reset"
    id: reset
    entity_category: config

  - platform: safe_mode
    name: "Safe Mode"
    internal: false
    entity_category: config

# Dual-point Climate Controller
climate:
  - platform: thermostat
    name: "Thermostat Climate Controller"
    sensor: temperature_sensor  # Reference the Home Assistant sensor ID here
    cool_deadband: 2 °F
    cool_overrun: 2 °F
    heat_deadband: 2 °F
    heat_overrun: 2 °F
    min_cooling_off_time: 0s
    min_cooling_run_time: 0s
    min_heating_off_time: 0s
    min_heating_run_time: 0s
    min_fanning_off_time: 0s
    min_fanning_run_time: 0s
    min_idle_time: 0s
    set_point_minimum_differential: 3 °F
    
    cool_action:
      - switch.turn_on: Y1
      - switch.turn_off: W1
      - switch.turn_off: W2
      - light.turn_off:
          id: hvac_status_led

      - light.turn_on:
          id: hvac_status_led
          red: 0
          green: 0
          blue: 80% 

    heat_action:
      - switch.turn_on: W1
      - switch.turn_off: Y1
      - light.turn_on:
          id: hvac_status_led
          red: 80%
          green: 0
          blue: 0
    max_heating_run_time: 300s

    supplemental_heating_delta: 2 °F
    supplemental_heating_action: 
      - switch.turn_on: W2
      - switch.turn_off: Y1

      - light.turn_on:
          id: hvac_status_led
          red: 80%
          green: 40%
          blue: 0

    idle_action:
      - switch.turn_off: G
      - switch.turn_off: W1
      - switch.turn_off: W2
      - switch.turn_off: Y1

      - light.turn_off:
          id: hvac_status_led
          #red: 0
          #green: 0
          #blue: 0 

    fan_only_action: 
      - switch.turn_on: G
      - switch.turn_off: W1
      - switch.turn_off: W2
      - switch.turn_off: Y1

      - light.turn_on:
          id: hvac_status_led
          red: 0
          green: 80%
          blue: 0  

    fan_with_cooling: True
    fan_with_heating: True
    default_preset: Home
    on_boot_restore_from: memory
    preset:
      - name: Home
        default_target_temperature_low: 68 °F
        default_target_temperature_high: 78 °F
        mode: HEAT_COOL
      - name: Comfort
        default_target_temperature_low: 70 °F
        default_target_temperature_high: 74 °F
        mode: HEAT_COOL
      - name: Sleep
        default_target_temperature_low: 65 °F
        default_target_temperature_high: 70 °F
        mode: HEAT_COOL
      - name: Away
        default_target_temperature_low: 50 °F
        default_target_temperature_high: 85 °F
        mode: HEAT_COOL
      - name: OverCool
        default_target_temperature_low: 60 °F
        default_target_temperature_high: 65 °F
        mode: COOL
